// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV_8hjs9IQr_hBHqhKzhLT4retINF51E8',
    appId: '1:278586592674:web:3303cd2effebe87f3b76fb',
    messagingSenderId: '278586592674',
    projectId: 'appointments-7e201',
    authDomain: 'appointments-7e201.firebaseapp.com',
    storageBucket: 'appointments-7e201.firebasestorage.app',
    measurementId: 'G-YH5Z7RBWVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdTV18bfo7LXiAWUPBXY3cOcFAsXyOjE',
    appId: '1:278586592674:android:a0993fa42254ccb23b76fb',
    messagingSenderId: '278586592674',
    projectId: 'appointments-7e201',
    storageBucket: 'appointments-7e201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLRtZR7EzPTRAWpKzdD9buzuW2Hyse0I',
    appId: '1:278586592674:ios:8950b87a4ee9a22b3b76fb',
    messagingSenderId: '278586592674',
    projectId: 'appointments-7e201',
    storageBucket: 'appointments-7e201.firebasestorage.app',
    iosBundleId: 'com.example.next',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV_8hjs9IQr_hBHqhKzhLT4retINF51E8',
    appId: '1:278586592674:web:18562557dec572d03b76fb',
    messagingSenderId: '278586592674',
    projectId: 'appointments-7e201',
    authDomain: 'appointments-7e201.firebaseapp.com',
    storageBucket: 'appointments-7e201.firebasestorage.app',
    measurementId: 'G-J0B8197DZ1',
  );
}
